name: cable
channels:
    - defaults
    - nvidia
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - numpy
    - scipy
    - h5py
    - matplotlib
    - scikit-learn
    - jupyter
    - tqdm
    - Cython
    - protobuf=3.20.*
    - pytorch=1.12.1
    - jax=0.3.16
    - jaxlib=0.3.15=*cuda*
    - cudatoolkit=11.3
    - cuda-nvcc=11.3
    - cudnn
    - faiss-gpu=1.7.2
    - pip:
        - flax==0.6.0
        - optax==0.1.3
        - distrax==0.1.2
        - einops
        - dill
        - seaborn
        - absl-py
        - gym
        - wandb==0.13.5
        - ml_collections
        - jupyter_http_over_ws
        - pypylon
        - pyquaternion
        - pyrealsense2
        - torchvision
        - opencv-python
        - pytimedinput
