name: cable
channels:
    - defaults
    - nvidia
    - conda-forge
dependencies:
    - python=3.10.9
    - pip
    - numpy
    - scipy
    - h5py
    - matplotlib
    - scikit-learn
    - jupyter
    - tqdm
    - Cython
    - protobuf=3.20.*
    - pytorch=1.12.1
    - cudatoolkit=11.3
    - cuda-nvcc=11.3
    - jax=0.3.16
    - jaxlib=0.3.15=*cuda*
    - cudnn
    - faiss-gpu=1.7.2
    - torchvision
    - flax
    - pip:
        - cloudpickle
        - einops
        - dill
        - seaborn
        - absl-py
        - wandb==0.13.5
        - ml_collections